# Import bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import dataset

In [2]:
dados_brutos = pd.read_csv('base_dados_brutos_tratados.csv')

# Análise explanatória dos dados

In [3]:
dados_brutos.head()

,npf,nome_sessao,quarto_jg,vel_max,dits_total,sprints,zv1,zv2,zv3,zv4,...,dif,tempo,temp,ac_total,acmi,aci,dc_total,dci,dcmi,dif_duo
0,709286,22.10.15_Flamengo,2,26.9,1208,16,369,435,194,134,...,-12,4.9,22_23,153,102,29,165,28,109,1
1,703092,22.10.15_Flamengo,3,27.0,662,9,187,251,105,55,...,-12,3.1,22_23,90,58,12,96,20,59,1
2,709286,22.10.15_Flamengo,3,26.7,1985,30,664,580,412,171,...,-12,10.0,22_23,235,183,65,268,60,203,1
3,709202,22.10.15_Flamengo,2,25.6,407,8,126,151,57,43,...,-12,1.9,22_23,80,56,11,81,11,56,1
4,709286,22.10.15_Flamengo,4,27.9,1867,22,555,614,397,130,...,-12,10.0,22_23,227,162,51,247,52,165,1

In [4]:
dados_brutos['interv_dias'].isnull().sum()

np.int64(67)

In [5]:
dados_brutos.shape

(4628, 44)

In [6]:
dados_brutos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4628 entries, 0 to 4627
Data columns (total 44 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   npf            4628 non-null   int64
 1   nome_sessao    4628 non-null   object
 2   quarto_jg      4628 non-null   int64
 3   vel_max        4628 non-null   float64
 4   dits_total     4628 non-null   int64
 5   sprints        4628 non-null   int64
 6   zv1            4628 non-null   int64
 7   zv2            4628 non-null   int64
 8   zv3            4628 non-null   int64
 9   zv4            4628 non-null   int64
 10  zv5            4628 non-null   int64
 11  dcel1          4628 non-null   int64
 12  dcel2          4628 non-null   int64
 13  dcel3          4628 non-null   int64
 14  dcel4          4628 non-null   int64
 15  acel1          4628 non-null   int64
 16  acel2          4628 non-null   int64
 17  acel3          4628 non-null   int64
 18  acel4          4628 non-null   int64
 19  fc1            4628 non-null   int64
 20  fc2            4628 non-null   int64
 21  fc3            4628 non-null   int64
 22  fc4            4628 non-null   int64
 23  fc5            4628 non-null   int64
 24  fc_80          4628 non-null   int64
 25  trimp          4628 non-null   int64
 26  dai            4628 non-null   int64
 27  dmi            4628 non-null   float64
 28  adversario     4628 non-null   object
 29  idade          4628 non-null   int64
 30  classificacao  4628 non-null   int64
 31  interv_dias    4561 non-null   float64
 32  mando          4628 non-null   int64
 33  posicao        4628 non-null   int64
 34  dif            4628 non-null   int64
 35  tempo          4628 non-null   float64
 36  temp           4628 non-null   object
 37  ac_total       4628 non-null   int64
 38  acmi           4628 non-null   int64
 39  aci            4628 non-null   int64
 40  dc_total       4628 non-null   int64
 41  dci            4628 non-null   int64
 42  dcmi           4628 non-null   int64
 43  dif_duo        4628 non-null   int64
dtypes: float64(4), int64(37), object(3)
memory usage: 1.6+ MB

# Análise exploratória dos dados

In [7]:
dados_brutos.isnull().sum()

npf               0
nome_sessao       0
quarto_jg         0
vel_max           0
dits_total        0
sprints           0
zv1               0
zv2               0
zv3               0
zv4               0
zv5               0
dcel1             0
dcel2             0
dcel3             0
dcel4             0
acel1             0
acel2             0
acel3             0
acel4             0
fc1               0
fc2               0
fc3               0
fc4               0
fc5               0
fc_80             0
trimp             0
dai               0
dmi               0
adversario        0
idade             0
classificacao     0
interv_dias      67
mando             0
posicao           0
dif               0
tempo             0
temp              0
ac_total          0
acmi              0
aci               0
dc_total          0
dci               0
dcmi              0
dif_duo           0
dtype: int64

In [8]:
dados_brutos.dropna(inplace=True)

In [9]:
dados_brutos['interv_dias'].isnull().sum()

np.int64(0)

In [10]:
dados_brutos.shape

(4561, 44)

In [11]:
dados_brutos.columns

Index(['npf', 'nome_sessao', 'quarto_jg', 'vel_max', 'dits_total', 'sprints',
       'zv1', 'zv2', 'zv3', 'zv4', 'zv5', 'dcel1', 'dcel2', 'dcel3', 'dcel4',
       'acel1', 'acel2', 'acel3', 'acel4', 'fc1', 'fc2', 'fc3', 'fc4', 'fc5',
       'fc_80', 'trimp', 'dai', 'dmi', 'adversario', 'idade', 'classificacao',
       'interv_dias', 'mando', 'posicao', 'dif', 'tempo', 'temp', 'ac_total',
       'acmi', 'aci', 'dc_total', 'dci', 'dcmi', 'dif_duo'],
      dtype='object')

## Descrição das variaveis:

- npf: numero de matrícula do atleta

- nome_sessao: codigo do jogo

- quarto_jg: quarto do jogo (1°, 2°, 3° e 4°)

- vel_max: velocidade máxima (em km/h)

- sprint: n° de vezes que o jogador passa 24km/h

- zv1: Distancia percorrida 3 - 6 km/h

- zv2: Distancia percorrida 6,01 - 12 km/h

- zv3: Distancia percorrida 12,01 - 18 km/h

- zv4: Distancia percorrida 18,01 - 24 km/h

- zv5: Distancia percorrida 24,01+ km/h

- dmi: Distancia percorrida 12,01+ km/h (Soma da zv3, zv4 e zv5)

- dai: Distancia percorrida 18,01+ km/h (Soma da zv4 e zv5)

- dcel1: -0.50 – -0.99 [m/s²]

- dcel2: -1.00 – -1.99 [m/s²]

- dcel3: -2.00 – -2.99 [m/s²]

- dcel4: -3.00 – -50.00 [m/s²]

- acel1: 0.50 – 0.99 [m/s²]

- acel2: 1.00 – 1.99 [m/s²]

- acel3: 2.00 – 2.99 [m/s²]

- acel4: 3.00 – 50.00 [m/s²]

- fc1: Tempo de permanecia entre 50 - 59% da FC máx do atleta

- fc2: Tempo de permanecia entre 60 - 69% da FC máx do atleta

- fc3: Tempo de permanecia entre 70 - 79% da FC máx do atleta

- fc4: Tempo de permanecia entre 80 - 89% da FC máx do atleta

- fc5: Tempo de permanecia entre 90 - 100% da FC máx do atleta

- fc_80: Tempo de permanecia entre 80 - 100% da FC máx do atleta (Soma de fc4 e fc5)

- trimp: Indice de estresse cardiovascular. Pondera o tempo em cada zona de FC pelo peso da zona (TRIMP = (fc1 * 1) + (fc2 * 2) + (fc3 * 3) + (fc4 * 4) + (fc5 * 5))

- adversario: Nome do adversário na partida

- idade: Idade do jogador no dia da partida

- classificacao: Classificação do time ao final do campeonato

- interv_dias: Intervalo de dias da partida atual em relação à anterior

- mando: Jogos realizados em casa (mando 2) e na casa do adversário (mando 1)

- posicao: Posição do atleta na equipe, sendo: Ala = 1, Pivô = 2 e Armador = 3

- dif: Diferença no placar final do jogo

- tempo: Tempo de permanencia em quadra

# Analise descritiva dos dados para incluir nos resultados do artigo

In [12]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_brutos.groupby('quarto_jg')[['dits_total', 'zv3', 'dmi', 'dai']].agg(formatar_media_std)
)

print(relatorio_final)

              dits_total           zv3            dmi          dai
quarto_jg
1          867.1 ± 315.7  154.1 ± 74.9  210.0 ± 110.1  55.9 ± 43.3
2          972.5 ± 346.0  153.7 ± 75.0  214.2 ± 113.4  60.4 ± 47.5
3          910.4 ± 357.5  145.9 ± 74.7  199.9 ± 111.7  54.0 ± 45.2
4          996.9 ± 437.1  146.4 ± 82.0  199.0 ± 122.2  52.6 ± 47.7

In [13]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_brutos.groupby('quarto_jg')[['ac_total', 'acel2', 'acmi', 'aci']].agg(formatar_media_std)
)

print(relatorio_final)

               ac_total        acel2          acmi          aci
quarto_jg
1          132.5 ± 42.3  67.6 ± 21.7   89.9 ± 29.0   22.3 ± 9.7
2          149.5 ± 46.8  77.2 ± 25.4   99.8 ± 32.9   22.6 ± 9.9
3          143.3 ± 49.7  74.1 ± 26.2   95.9 ± 33.9  21.9 ± 10.2
4          161.4 ± 64.1  84.5 ± 34.2  107.1 ± 43.4  22.6 ± 11.7

In [14]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_brutos.groupby('quarto_jg')[['dc_total', 'dcel2', 'dcmi', 'dci']].agg(formatar_media_std)
)

print(relatorio_final)

               dc_total        dcel2          dcmi          dci
quarto_jg
1          137.8 ± 44.5  66.8 ± 20.9   91.4 ± 29.1  24.6 ± 10.3
2          153.9 ± 49.1  76.7 ± 23.9  102.6 ± 32.8  25.9 ± 10.9
3          148.1 ± 52.0  72.9 ± 25.6   98.0 ± 34.7  25.1 ± 10.9
4          165.9 ± 66.3  84.0 ± 33.3  110.6 ± 44.4  26.6 ± 13.1

In [16]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_brutos.groupby('quarto_jg')[['trimp']].agg(formatar_media_std)
)

print(relatorio_final)

                 trimp
quarto_jg
1          49.2 ± 18.5
2          62.9 ± 20.7
3          54.8 ± 21.1
4          63.2 ± 28.0